- name: lamp installation on ubuntu & centOS
  become: yes
  hosts: all
  tasks:
    - name: update cache & install apache2
      ansible.builtin.apt:
        name: 
          - apache2
            
        update_cache: yes
        state: present
    - name: installing php
      ansible.builtin.apt:
        name: 
          - php 
            libapache2-mod-php 
            php-mysql
        state: present
    - name: creating info.php file
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
  # handlers: