---
- name: Install tomcat 10
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.package:
        name: "{{ java_default_version }}"
        name: tomcat
        state: present
      