---
- name: Install tomcat 10
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.package:
        name: "{{ java_default_version }}"
        state: present
    - name: creating the tomcat group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
      