---
- name: Install tomcat 10
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.package:
        name: "{{ java_default_version }}"
        state: present
    - name: creating the tomcat group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: creating user 
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: true
        group: "{{ group_name }}"
        home: "{{ home_dir }}"
        shell: "{{ shell }}"
        state: present
    - name: downloading tomcat & untaring
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: yes